[package]
name = "himewm_layout"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.217", features = ["derive"] }
serde_json = { version = "1.0.145", features = ["raw_value"] }
windows = { version = "0.59.0", features = ["Win32_Graphics_Gdi"] }
